apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: standard-rwx      
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain	  # Delete
  csi:
      driver: filestore.csi.storage.gke.io
      volumeHandle: "kwon0717"
      volumeAttributes:
        ip: "10.125.91.194"
        volume: "nfs_shared"  
