apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain	  # Delete
  nfs:
    server: 10.232.149.18
    path: /nfs_shared
